# Generated by Django 4.2.7 on 2023-11-16 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="rating",
            old_name="userid",
            new_name="user",
        ),
    ]
