# Generated by Django 4.2.7 on 2023-11-18 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_attendance_date_lastattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="lastattendance",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
